@startuml

scale 1.1

skinparam {
    defaultTextAlignment center
}

rectangle Thread
rectangle Subclasses
rectangle "sealed\nBaseVirtualThread" as BaseVirtualThread
rectangle "final\nVirtualThread" as VirtualThread

Thread -down- Subclasses
Thread -down- BaseVirtualThread
BaseVirtualThread -down- VirtualThread

@enduml
