sequenceDiagram
    x->>PlatformThread1: request 1
    activate PlatformThread1
    PlatformThread1->>Service: Hello
    deactivate PlatformThread1
    activate Service

    activate PlatformThread1


    Service->>PlatformThread1: Great!
    deactivate PlatformThread1
    deactivate Service
    activate PlatformThread1
    PlatformThread1->>x: response 1
    deactivate PlatformThread1


