@startuml

skinparam {
    defaultTextAlignment center
    roundCorner 0
    CardBackgroundColor transparent
    RectangleBackgroundColor transparent
    RectangleFontName Source Sans Pro
}

rectangle JVM {
  card "plarform\nthread" as PlatformThread1
  card "plarform\nthread" as PlatformThread2
  card "plarform\nthread" as PlatformThread3
}

rectangle "operation system" {
  card "OS\nthread" as OsThread1
  card "OS\nthread" as OsThread2
  card "OS\nthread" as OsThread3
}

OsThread1 -up- PlatformThread1
OsThread2 -up- PlatformThread2
OsThread3 -up- PlatformThread3

@enduml
