@startuml

title I/O multiplexing model

scale 1.1
hide footbox
skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam titleFontSize 15
skinparam sequenceMessageAlign left
skinparam participantBackgroundColor #white
skinparam noteBackgroundColor #white
skinparam sequenceGroupBackgroundColor #white

activate HW
rnote over HW : Fill buffer 0
HW -> IRQ
deactivate HW
IRQ -[hidden]> HW
activate HW
rnote over HW : Fill buffer 1
HW -> IRQ
deactivate HW
@enduml
