@startuml

skinparam {
    defaultTextAlignment center
    roundCorner 0
    CardBackgroundColor transparent
    RectangleBackgroundColor transparent
    RectangleFontName Source Sans Pro
    RectangleFontStyle normal
}

card "\n" as GT1 #green
card "\n" as GT2 #green
card "\n" as GT3 #green
card "\n" as GT4 #green
card "\n" as GT5 #green
card "\n" as GT6 #green
card "\n" as GT7 #green
card "\n" as GT8 #green
card "\n" as GT9 #green
card "\n" as GT10 #green
card "\n" as GT11 #green
card "\n" as GT12 #green
card "\n" as GT13 #green
card "\n" as GT14 #green
card "\n" as GT15 #green
card "\n" as GT16 #green


rectangle "\n\t\n\t\n\t" as PT1 #navy
rectangle "\n\t\n\t\n\t" as PT2
rectangle "\n\t\n\t\n\t" as PT3
rectangle "\n\t\n\t\n\t" as PT4

GT1-right[hidden]-GT2
GT2-right[hidden]-GT3
GT3-right[hidden]-GT4
GT4-right[hidden]-GT5
GT5-right[hidden]-GT6
GT6-right[hidden]-GT7
GT7-right[hidden]-GT8

GT9-right[hidden]-GT10
GT10-right[hidden]-GT11
GT11-right[hidden]-GT12
GT12-right[hidden]-GT13
GT13-right[hidden]-GT14
GT14-right[hidden]-GT15
GT15-right[hidden]-GT16

GT1-down[hidden]-GT9
GT8-down[hidden]-GT16

GT12-down[hidden]-PT1
GT13-down[hidden]-PT1

PT1-right[hidden]-PT2
PT2-right[hidden]-PT3
PT3-right[hidden]-PT4

@enduml
