@startuml

scale 1.0

skinparam useBetaStyle true

<style>
    .transparentBorder {
        LineColor transparent
    }
}
</style>

skinparam {
    defaultTextAlignment center
    roundCorner 0
    RectangleBackgroundColor transparent
    RectangleFontName Arial
}

rectangle Thread
rectangle SubClass1
rectangle SubClass2
rectangle "..." as SubClass3 <<transparentBorder>>
rectangle SubClassN
rectangle "sealed\nBaseVirtualThread" as BaseVirtualThread
rectangle "final\nVirtualThread" as VirtualThread

Thread -down- SubClass1
Thread -down- SubClass2
Thread -down[#transparent]- SubClass3
Thread -down- SubClassN
Thread -down- BaseVirtualThread
BaseVirtualThread -down- VirtualThread

@enduml
