@startuml

skinparam {
'    linetype ortho
    defaultTextAlignment center
    roundCorner 0
    CardBackgroundColor transparent
    RectangleBackgroundColor transparent
    RectangleFontName Source Sans Pro
    RectangleFontStyle normal
}

rectangle JVM {
  card "virtual\nthread" as VirtualThread1
  card "virtual\nthread" as VirtualThread2
  card "virtual\nthread" as VirtualThread3
  card "virtual\nthread" as VirtualThread4

  VirtualThread1 -right[hidden]- VirtualThread2
  VirtualThread2 -right[hidden]- VirtualThread3
  VirtualThread3 -right[hidden]- VirtualThread4

  rectangle "JMV scheduler" #line.dashed {
    card "сarrier\nthread" as CarrierThread1
    card "сarrier\nthread" as CarrierThread2
    card "сarrier\nthread" as CarrierThread3
  }
}

rectangle "operation system" {
  card "OS\nthread" as OsThread1
  card "OS\nthread" as OsThread2
  card "OS\nthread" as OsThread3
}

OsThread1 -up- CarrierThread1
OsThread2 -up- CarrierThread2
OsThread3 -up- CarrierThread3

CarrierThread1 -up- VirtualThread1
CarrierThread2 -up- VirtualThread2
CarrierThread3 -up- VirtualThread3

@enduml
