@startuml

scale 1.0
hide footbox
'!pragma teoz true

'skinparam monochrome true
'skinparam defaultFontName Source Sans Pro
'skinparam titleFontSize 15
'skinparam titleFontStyle normal
'skinparam sequenceMessageAlign left
'skinparam participantBackgroundColor #white
'skinparam noteBackgroundColor #white
'skinparam sequenceGroupBackgroundColor #white

skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam titleFontSize 15
skinparam sequenceMessageAlign center

participant "virtual\nthread" as VirtualThread1
participant "continuation" as CarrierThread
participant "operation\nsystem" as Service

'Note right of kernel: wait for data\nin at least one\ndescriptor

activate VirtualThread1
VirtualThread1->>CarrierThread : run()
activate CarrierThread
||40||
VirtualThread1->>CarrierThread : yield()
CarrierThread->>VirtualThread1
deactivate CarrierThread
||20||
VirtualThread1->>Service
deactivate VirtualThread1
activate Service

||80||

Service->>VirtualThread1
deactivate Service
activate VirtualThread1

VirtualThread1->>CarrierThread : run()
activate CarrierThread
||40||
CarrierThread->>VirtualThread1
deactivate CarrierThread
deactivate VirtualThread1

@enduml
