@startuml

skinparam {
    defaultTextAlignment center
    roundCorner 0
    CardBackgroundColor transparent
    RectangleBackgroundColor transparent
    RectangleFontName Source Sans Pro
}

rectangle JVM {
  rectangle PlatformThread1
  rectangle PlatformThread2
  rectangle PlatformThread3

  rectangle "JMV scheduler" {
    rectangle "сarrier\nthread" as CarrierThread1
    rectangle "сarrier\nthread" as CarrierThread2
    rectangle "сarrier\nthread" as CarrierThread3
  }
}

rectangle "Operation system" {
  rectangle "OS thread" as OsThread1
  rectangle "OS thread" as OsThread2
  rectangle "OS thread" as OsThread3
}

OsThread1 -up- CarrierThread1
OsThread2 -up- CarrierThread2
OsThread3 -up- CarrierThread3

CarrierThread1 -up- PlatformThread1
CarrierThread2 -up- PlatformThread2
CarrierThread3 -up- PlatformThread3

@enduml
